Accounts/urls.py
from django.urls import path
from . import views

app_name = 'Accounts'
urlpatterns=[
    path('<template_name>/',views.listView.as_view(),name='accounts'),
    path('create/<template_name>/',views.createView.as_view(),name='create'),
    path('update/<str:template_name>/<int:pk>/',views.updateView.as_view(),name='update'),
    path('delete/<str:template_name>/<int:pk>/',views.deleteView.as_view(),name='delete'),
]

Core/urls.py
from django.urls import path,include
from . import views

urlpatterns=[
    path('',views.Home,name='Home'),
    path('Stocked/',include('Stocked.urls'),name='Stocked'),
    path('Accounts/',include('Accounts.urls'),name='Accounts'),
    path('Bills/',include('Bills.urls'),name='Bills')
]

Pos/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Core.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

Stocked/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
app_name = 'Stocked'

urlpatterns=[
    path('<template_name>/',views.listView.as_view(),name='Stocked'),
    path('create/<template_name>/',views.createView.as_view(),name='create'),
    path('update/<str:template_name>/<int:pk>/',views.updateView.as_view(),name='update'),
    path('delete/<str:template_name>/<int:pk>/',views.deleteView.as_view(),name='delete'),
]
urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

Core/views.py
from django.shortcuts import render
# Create your views here.

def Home(request):
    Context ={
        'Breadcrumbs':{'Home':'Home.html'},
      }
    return render(request,'Home.html',Context)

Core/templates/includes/dialog.html
 <!-- Logout Modal-->
 <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-danger text-white">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close text-white" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-danger" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>
<!-- New Category Modal -->
  <div class="modal fade" id="NewCategoriesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="exampleModalLabel">
                    <i class="fa fa-plus"></i>
                    New Category
                </h5>
                <button class="close text-white" type="button" data-dismiss="modal" aria-label="close"> 
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form action="">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="Unit_name">Category Name</label>
                        <input type="text" name="Category_name" id="Category_name" class="form-control" placeholder="Category Name">
                    </div>
                    <div class="form-group">
                        <label for="Brand_type">Brand type</label>
                        <select class="form-control text-primary" id="Brand_type" name="Brand_type" required>
                          <option disabled selected><sub>Please select a product type</sub></option>
                          <option>Speakers</option>
                          <option>Card Readers</option>
                          <option>Headphones & MICs</option>
                          <option>Mousepads</option>
                          <option>Mice &amp; Pointing Devices</option>
                          <option>Display Monitors</option>
                          <option>Keyboards</option>
                          <option>Cables & Chargers</option>
                          <option>Power Supplies</option>
                        </select>
                        <small class="float-right">Brand not listed here? <a href="#"data-toggle="modal" data-target="#NewBrandModel">Add new</a></small>
                    </div>
                    <div class="form-group">
                        <label for="Store_note">Note <small class="text-muted">(Optional)</small></label>
                        <textarea class="form-control" name="Store_note"  id="Store_note" rows="8" cols="80" placeholder="Add some note or description about this store..."></textarea>
                    </div>
                    <small class="text-muted"><em>Please double check information before submitting.</em></small>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">
                        Cancel
                    </button>
                    <input type="submit" value="Add Store" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
  </div>
  <!-- New Product Model -->
  <div class="modal fade h-100 overflow-hidden pb-4" id="NewProductsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg h-100 overflow-hidden" role="document">
      <div class="modal-content h-100 overflow-hidden"> 
        <div class="modal-header bg-primary text-white">
          <h5 class="modal-title" id="exampleModalLabel">
            <i class="fa fa-plus"></i>
            New Product
        </h5>
        <button class="close text-white" type="button" data-dismiss="modal" aria-label="close"> 
            <span aria-hidden="true">×</span>
        </button>
        </div>
        <form action="" class="h-100 overflow-auto">
          <div class="modal-body">
            <div class="form-group">
                <label for="Unit_name">Product Name</label>
                <input type="text" name="Product_name" id="Product_name" class="form-control" placeholder="Product Name">
            </div>
            <div class="form-group">
                <label for="Product_code">Code</label>
                <input type="text" name="Product_code" id="Product_code" class="form-control" placeholder="Product Code">
                <small class="text-muted">IMEI</small>
            </div>
            <div class="form-group">
                <label for="Barcode">Barcode</label>
                <input type="text" name="Barcode" id="Barcode" class="form-control" placeholder="Barcode">
                <small class="text-muted">IMEI</small>
            </div>
            <div class="form-group">
              <label for="Brand_type">Brand type</label>
              <select class="form-control text-primary" id="Brand_type" name="Brand_type" required>
                <option disabled selected><sub>Please select a product type</sub></option>
                <option>Speakers</option>
                <option>Card Readers</option>
                <option>Headphones & MICs</option>
                <option>Mousepads</option>
                <option>Mice &amp; Pointing Devices</option>
                <option>Display Monitors</option>
                <option>Keyboards</option>
                <option>Cables & Chargers</option>
                <option>Power Supplies</option>
              </select>
              <small class="float-right">Brand not listed here? <a href="#"data-toggle="modal" data-target="#NewBrandModel">Add new</a></small>
            </div>
            <div class="form-group">
              <label for="Category">Category type</label>
              <select class="form-control text-primary" id="Category" name="Category" required>
                <option disabled selected><sub>Please select a Category</sub></option>
                <option>Speakers</option>
                <option>Card Readers</option>
                <option>Headphones & MICs</option>
                <option>Mousepads</option>
                <option>Mice &amp; Pointing Devices</option>
                <option>Display Monitors</option>
                <option>Keyboards</option>
                <option>Cables & Chargers</option>
                <option>Power Supplies</option>
              </select>
              <small class="float-right">Category not listed here? <a href="#"data-toggle="modal" data-target="#NewCategoryModal">Add new</a></small>
            </div>
            <div class="form-group">
              <label for="Purchase_price">Purchase Price</label>
              <input type="number" class="form-control" name="Purchase_price" value="Purchase_price" placeholder="Enter Purchase price here..." required>
            </div>
            <div class="form-group">
              <label for="Sale_price">Sale Price</label>
              <input type="number" class="form-control" name="Sale_price" value="Sale_price" placeholder="Enter Sale price here..." required>
            </div>
            <div class="form-group">
              <label for="Purchase_unit">Purchase Unit</label>
              <select class="form-control text-primary" id="Purchase_unit" name="Purchase_unit" required>
                <option disabled selected><sub>Please select a Unit</sub></option>
                <option>Speakers</option>
                <option>Card Readers</option>
                <option>Headphones & MICs</option>
                <option>Mousepads</option>
                <option>Mice &amp; Pointing Devices</option>
                <option>Display Monitors</option>
                <option>Keyboards</option>
                <option>Cables & Chargers</option>
                <option>Power Supplies</option>
              </select>
              <small class="float-right">Unit not listed here? <a href="#"data-toggle="modal" data-target="#NewUnitModal">Add new</a></small>
            </div>
            <div class="form-group">
              <label for="Sale_unit">Sale Unit</label>
              <select class="form-control text-primary" id="Sale_unit" name="Sale_unit" required>
                <option disabled selected><sub>Please select a Unit</sub></option>
                <option>Speakers</option>
                <option>Card Readers</option>
                <option>Headphones & MICs</option>
                <option>Mousepads</option>
                <option>Mice &amp; Pointing Devices</option>
                <option>Display Monitors</option>
                <option>Keyboards</option>
                <option>Cables & Chargers</option>
                <option>Power Supplies</option>
              </select>
              <small class="float-right">Unit not listed here? <a href="#"data-toggle="modal" data-target="#NewUnitModal">Add new</a></small>
            </div>
            <div class="form-group">
                <label for="image">Image<small class="text-muted">(Optional)</small></label>
                <input type="file" name="image" id="image" class="form-control-file">
            </div>
            <div class="form-group">
                <label for="Store_note">Note <small class="text-muted">(Optional)</small></label>
                <textarea class="form-control" name="Store_note"  id="Store_note" rows="8" cols="80" placeholder="Add some note or description about this store..."></textarea>
            </div>
            <small class="text-muted"><em>Please double check information before submitting.</em></small>
        </div>
        <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">
                Cancel
            </button>
            <input type="submit" value="Add Store" class="btn btn-primary">
        </div>
        </form>
      </div>
    </div>
  </div>

Core/templates/includes/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

Core/templates/includes/header.html
<nav class="navbar navbar-expand navbar-dark bg-primary static-top">
    <a class="navbar-brand mr-1" href="{% url 'Home' %}">WTA_Pos</a>
    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fa fa-bars"></i>
    </button>
    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-plus fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#NewProductsModal"> <i class="fa fa-tag"></i> New Product</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#NewCategoriesModal"> <i class="fa fa-tags"></i> New Category</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-flash fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Products' %}"> <i class="fa fa-tag"></i> All Products</a>
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Categories' %}"> <i class="fa fa-tags"></i> All Categories</a>
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Stores' %}"> <i class="fa fa-tags"></i> All Stores</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow ml-3">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="badge badge-warning">9+</span>
          <i class="fa fa-fw fa-bell"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item text-danger no-text-decorations" href="#"> <i class="fa fa-info-circle"></i> You've few blocked products</a>
          <a class="dropdown-item text-danger no-text-decorations" href="#"> <i class="fa fa-info-circle"></i> Another new notification</a>
          <a class="dropdown-item text-danger no-text-decorations" href="#"> <i class="fa fa-info-circle"></i> Another new notification</a>
          <a class="dropdown-item text-danger no-text-decorations" href="#"> <i class="fa fa-info-circle"></i> Another new notification</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="">See more notifications</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow ml-3">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <div class="dropdown-header">Akram Qasem</div>
          <a class="dropdown-item" href="#"> <i class="fa fa-user"></i> Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"> <i class="fa fa-cog"></i> Settings</a>
          <a class="dropdown-item" href="#"> <i class="fa fa-line-chart"></i> Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal"> <i class="fa fa-power-off"></i> Logout</a>
        </div>
      </li>
    </ul>
</nav>

Core/templates/includes/scripts.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/jquery.dataTables.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'js/datatables-demo.js' %}"></script>
<script src="{% static 'js/rc-pos.min.js' %}"></script>
<script src="{% static 'js/code.js' %}"></script>

Core/templates/includes/sidebar.html
<ul class="sidebar navbar-nav bg-dark">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'Home' %}">
        <i class="fa fa-fw fa-home"></i>
        <span>Home</span>
      </a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="StoresDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-folder"></i>
          <span>
            Accounts
            <i class="float-right fa fa-angle-down"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="StoresDropdown">
          <h6 class="dropdown-header">Customers</h6>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#addProductModal"> <i class="fa fa-plus"></i> Add Customer</a>
          <a class="dropdown-item" href="{% url 'Accounts:accounts' 'Customers' %}"> <i class="fa fa-tags"></i> All Customers</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Supplyrs</h6>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#addProductTypeModal"> <i class="fa fa-plus"></i> Add Supplyr</a>
          <a class="dropdown-item" href="{% url 'Accounts:accounts' 'Suppliers' %}"> <i class="fa fa-tags"></i> All Supplyrs</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="StoresDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-folder"></i>
          <span>
            Stocking
            <i class="float-right fa fa-angle-down"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="StoresDropdown">
          <h6 class="dropdown-header">Products</h6>
          <a class="dropdown-item" href="{% url 'Stocked:create' 'Products' %}"> <i class="fa fa-user"></i> Add Product</a>
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Products' %}"> <i class="fa fa-tags"></i> All Products</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Stores</h6>
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Stores' %}"> <i class="fa fa-tags"></i> All Store</a>
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Units' %}"> <i class="fa fa-tags"></i> All Units</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Categories</h6>
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Categories' %}"> <i class="fa fa-tags"></i> All Categories</a>
          <a class="dropdown-item" href="{% url 'Stocked:Stocked' 'Brands' %}"> <i class="fa fa-tags"></i> Brands</a>
        </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <i class="fa fa-fw fa-cogs"></i>
        <span>General Settings</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <i class="fa fa-fw fa-life-ring"></i>
        <span>Help</span></a>
    </li>
</ul>