Accounts/urls.py
from django.urls import path
from . import views

app_name = 'Accounts'
urlpatterns=[
    path('<template_name>/',views.listView.as_view(),name='accounts'),
    path('create/<template_name>/',views.createView.as_view(),name='create'),
    path('update/<str:template_name>/<int:pk>/',views.updateView.as_view(),name='update'),
    path('delete/<str:template_name>/<int:pk>/',views.deleteView.as_view(),name='delete'),
]

Pos/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Core.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models

# Create your models here.

class Account(models.Model):
    accountType =(
        ('customer','customer'),
        ('supplier','supplier')
    )

    name = models.CharField(max_length=32)
    phone = models.CharField(max_length=16)
    address = models.CharField(max_length=16)
    note = models.CharField(max_length=64,blank=True,null=True)
    type = models.CharField(max_length=16,choices=accountType)

    def __str__(self) -> str:
        return self.name

Accounts/views.py
from typing import Any
from django.shortcuts import render,redirect
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from .models import Account 
# Create your views here.


class listView(ListView):
    template_name ='Accounts.html'
    def get_queryset(self) :
        model = Account
        account_type = self.kwargs['template_name'][:-1].lower()
        return model.objects.filter(type=account_type)
    
    def get_context_data(self):
        template_name = self.kwargs['template_name']
        object_lIst = self.get_queryset()
        Context ={'template':template_name,
              'Breadcrumbs':['Accounts',template_name],
              'object_list' : object_lIst}
        return Context
    

   
class createView(CreateView):
    fields = '__all__'
    template_name = 'create.html'
    
    def get_queryset(self) :
        model = Account
        account_type = self.kwargs['template_name'][:-1].lower()
        return model.objects.filter(type=account_type)
    
    def form_valid(self, form):
        form.save()
        template = self.kwargs['template_name']
        return redirect(f'http://127.0.0.1:8000/Accounts/{template}')

class updateView(UpdateView):
    fields = '__all__'
    template_name = 'update.html'

    def get_object(self):
        model = Account
        pk = self.kwargs['pk']
        return model.objects.get(pk=pk)
    
    def form_valid(self, form):
        form.save()
        template = self.kwargs['template_name']
        return redirect(f'http://127.0.0.1:8000/Accounts/{template}')
    
class deleteView(DeleteView):
    template_name = 'delete.html'

    def get_object(self):
        model = Account
        pk = self.kwargs['pk']
        return model.objects.get(pk=pk)
    
    def get_success_url(self) -> str:
        template = self.kwargs['template_name']
        return redirect(f'http://127.0.0.1:8000/Accounts/{template}')
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = {}
        if self.object :
            context['object'] = self.object
            context['CancelUrl'] = self.get_success_url()
        return context
    
    def delete(self,request,*args,**kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delet()
        return redirect(success_url)
        

Accounts/templates/Accounts.html
{% extends 'Home.html' %}

{% block content %}
    
<div class="card-body">
    <div class="table-responsive">
        {% if object_list %}
        <table class="table table-bordered " id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Note</th>
                    <th>Control</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Note</th>
                    <th>Control</th>
                </tr>
            </tfoot>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{object.pk}}</td>
                    <td>{{object.name}}</td>
                    <td>{{object.phone}}</td>
                    <td>{{object.address}}</td>
                    <td>{{object.note}}</td>
                    <td>
                    <div class="d-flex justify-content-around">
                        <a class="btn btn-sm btn-outline-info" href="{% url 'Accounts:update' template object.pk %}">update</a>
                        <a class="btn btn-sm btn-outline-danger" href="{% url 'Accounts:delete' template object.pk %}">delete</a>
                    </div>
                    </td>
                </tr>
                {%  endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No {{template}}!!!</p>
          {% endif %}
    </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>  
{% endblock content %}

Accounts/templates/create.html
{% extends 'Accounts.html' %}
{% block content %}
    <form action="" method="POST" class="card" enctype="multipart/form-data">
        <div class="card-header text-center text-primary">
            <h3 class="card-title">Create form</h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
        {{form.as_p}}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success w-100">Save</button>
        </div>
    </form>

{% endblock content %}

Accounts/templates/delete.html
{% extends 'Accounts.html' %}
{% block content %}
    <form action="" method="POST" class="card">
        <div class="card-header">
            <h2 class="text-danger card-title">Are you sure to delete?</h2>
        </div>
        <div class="card-body">
            {% csrf_token %}
        <table class="table table-bordered">
            <tr>
                <td>{{object.pk}}</td>
                <td>{{object.name}}</td>
                <td>{{object.note}}</td>
            </tr>
        </table>
        </div>
        <div class="d-flex justify-content-around card-footer">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-outline-info" href="{{ CancelUrl }}">Cancel</a>
        </div>
    </form>

{% endblock content %}

Accounts/templates/update.html
{% extends 'Accounts.html' %}
{% block content %}
    <form action="" method="POST" class="card">
        <div class="card-header text-center text-primary">
            <h3 class="card-title">Update form</h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
        {{form.as_p}}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success w-100">Save</button>
        </div>
    </form>

{% endblock content %}