Pos/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Core.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

Stocked/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
app_name = 'Stocked'

urlpatterns=[
    path('<template_name>/',views.listView.as_view(),name='Stocked'),
    path('create/<template_name>/',views.createView.as_view(),name='create'),
    path('update/<str:template_name>/<int:pk>/',views.updateView.as_view(),name='update'),
    path('delete/<str:template_name>/<int:pk>/',views.deleteView.as_view(),name='delete'),
]
urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

Stocked/models.py
from django.db import models

# Create your models here.

class Store(models.Model):
    name = models.CharField(max_length=32)
    location = models.CharField(max_length=64)
    note = models.TextField()

    def __str__(self):
        return self.name
    
class Unit(models.Model):
    name = models.CharField(max_length=32)
    code = models.CharField(max_length=4)
    note = models.TextField()

    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=32)
    note = models.TextField()

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=32)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    note = models.TextField()

    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=32)
    code = models.CharField(max_length=8)
    barcode = models.CharField(max_length=16)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    purchase_price = models.DecimalField(max_digits=9,decimal_places=2)
    sale_price = models.DecimalField(max_digits=9,decimal_places=2)
    purchase_unit = models.ForeignKey(Unit,on_delete=models.CASCADE,related_name='parchase_unit')
    sale_unit = models.ForeignKey(Unit,on_delete=models.CASCADE,related_name='sale_unit')
    note = models.TextField(max_length=64)
    image = models.ImageField(upload_to="pro_images/%y/%m/%d",default='pro_images/default.png',blank=True)
    

Stocked/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import redirect
from django.views.generic import UpdateView,DeleteView,CreateView,ListView
# Create your views here.
from .utility import *

class listView(ListView):
    template_name ='Stocked.html'
    def get_queryset(self) :
        model = get_list_by_template_name(self.kwargs['template_name'])
        return model.objects.all()
    
    def get_context_data(self):
        template_name = self.kwargs['template_name']
        object_lIst = self.get_queryset()
        Context ={'template':template_name,
              'Breadcrumbs':['Stocked',template_name],
              'object_list' : object_lIst}
        return Context
    
class createView(CreateView):
    fields = '__all__'
    template_name = 'control/create.html'
    
    def get_queryset(self) -> QuerySet[Any]:
        model = get_list_by_template_name(self.kwargs['template_name'])
        return model.objects.all()
    
    def form_valid(self, form):
        form.save()
        template = self.kwargs['template_name']
        return redirect(f'http://127.0.0.1:8000/Stocked/{template}')

class updateView(UpdateView):
    fields = '__all__'
    template_name = 'control/update.html'

    def get_object(self):
        model = get_list_by_template_name(self.kwargs['template_name'])
        pk = self.kwargs['pk']
        return model.objects.get(pk=pk)
    
    def form_valid(self, form):
        form.save()
        template = self.kwargs['template_name']
        return redirect(f'http://127.0.0.1:8000/Stocked/{template}')
    
class deleteView(DeleteView):
    template_name = 'control/delete.html'

    def get_object(self):
        model = get_list_by_template_name(self.kwargs['template_name'])
        pk = self.kwargs['pk']
        return model.objects.get(pk=pk)
    
    def get_success_url(self) -> str:
        template = self.kwargs['template_name']
        return f'http://127.0.0.1:8000/Stocked/{template}'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = {}
        if self.object :
            context['object'] = self.object
            context['CancelUrl'] = self.get_success_url()
        return context
    
    def delete(self,request,*args,**kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delet()
        return redirect(success_url)
        

Stocked/templates/includes/Brands.html
<div class="card-body">
    <div class="table-responsive">
      {% if object_list %}
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>BID</th>
            <th>Brand Name</th>
            <th>Note</th>
            <th>Control</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>BID</th>
            <th>Brand Name</th>
            <th>Note</th>
            <th>Control</th>
        </tfoot>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td>{{object.pk}}</td>
            <td>{{object.name}}</td>
            <td>{{object.note}}</td>
            <td>
              <div class="d-flex justify-content-around">
                <a class="btn btn-sm btn-outline-info" href="{% url 'Stocked:update' 'Brands' object.pk %}">update</a>
                <a class="btn btn-sm btn-outline-danger" href="{% url 'Stocked:delete' 'Brands' object.pk %}">delete</a>
              </div>
            </td>
          </tr>
          {%  endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No {{template}}!!!</p>
    {% endif %}
    </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Stocked/templates/includes/Categories.html
<div class="card-body">
  <div class="table-responsive">
    {% if object_list %}
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>CID</th>
          <th>Category Name</th>
          <th>Category Brand</th>
          <th>Note</th>
          <th>Control</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>CID</th>
          <th>Category Name</th>
          <th>Category Brand</th>
          <th>Note</th>
          <th>Control</th>
      </tfoot>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{object.pk}}</td>
            <td>{{object.name}}</td>
            <td>{{object.brand}}</td>
            <td>{{object.note}}</td>
            <td>
              <div class="d-flex justify-content-around">
                <a class="btn btn-sm btn-outline-info" href="{% url 'Stocked:update' 'Categories' object.pk %}">update</a>
                <a class="btn btn-sm btn-outline-danger" href="{% url 'Stocked:delete' 'Categories' object.pk %}">delete</a>
              </div>
            </td>
          </tr>
        {%  endfor %}
        </tbody>
      </table>
      {% else %}
        <p>No {{template}}!!!</p>
      {% endif %}
  </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Stocked/templates/includes/Products.html
<div class="card-body">
  <div class="table-responsive">
    {% if object_list %}
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>PID</th>
          <th>Name</th>
          <th>Code</th>
          <th>Barcode</th>
          <th>Brand</th>
          <th>Category</th>
          <th>Purchase price</th>
          <th>Sale price</th>
          <th>Purchase unit</th>
          <th>Sale unit</th>
          <th>Note</th>
          <th>image</th>
          <th>control</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{object.pk}}</td>
            <td>{{object.name}}</td>
            <td>{{object.code}}</td>
            <td>{{object.barcode}}</td>
            <td>{{object.category.brand}}</td>
            <td>{{object.category}}</td>
            <td>{{object.purchase_price}}</td>
            <td>{{object.sale_price}}</td>
            <td>{{object.purchase_unit}}</td>
            <td>{{object.sale_unit}}</td>
            <td>{{object.note|truncatechars_html:14}}</td>
            <td>
              {% if object.image %}
                <img src="{{ object.image.url }}" width="32" height="32" alt="">
              {% else %}
                <p>No image</p>
              {% endif %}
            </td>
            <td>
              <div class="d-flex justify-content-around">
                <a class="btn btn-sm btn-outline-info" href="{% url 'Stocked:update' 'Products' object.pk %}">update</a>
                <a class="btn btn-sm btn-outline-danger" href="{% url 'Stocked:delete' 'Products' object.pk %}">delete</a>
              </div>
            </td>
          </tr>
        {%  endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No {{template}}!!!</p>
    {% endif %}
  </div>
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Stocked/templates/includes/Stores.html
  <div class="card-body">
  <div class="table-responsive">
    {% if object_list %}
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>SID</th>
          <th>Store Name</th>
          <th>Store Location</th>
          <th>Note</th>
          <th>Control</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>SID</th>
          <th>Store Name</th>
          <th>Store Location</th>
          <th>Note</th>
          <th>Control</th>
      </tfoot>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{object.pk}}</td>
            <td>{{object.name}}</td>
            <td>{{object.location}}</td>
            <td>{{object.note}}</td>
            <td>
              <div class="d-flex justify-content-around">
                <a class="btn btn-sm btn-outline-info" href="{% url 'Stocked:update' 'Stores' object.pk %}">update</a>
                <a class="btn btn-sm btn-outline-danger" href="{% url 'Stocked:delete' 'Stores' object.pk %}">delete</a>
              </div>
            </td>
          </tr>
        {%  endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No {{template}}!!!</p>
    {% endif %}
  </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

Stocked/templates/includes/Units.html
<div class="card-body">
  <div class="table-responsive">
    {% if object_list %}
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>UID</th>
          <th>Unit Name</th>
          <th>Unit Code</th>
          <th>Note</th>
          <th>Control</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>UID</th>
          <th>Unit Name</th>
          <th>Unit Code</th>
          <th>Note</th>
          <th>Control</th>
      </tfoot>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{object.pk}}</td>
            <td>{{object.name}}</td>
            <td>{{object.code}}</td>
            <td>{{object.note}}</td>
            <td>
              <div class="d-flex justify-content-around">
                <a class="btn btn-sm btn-outline-info" href="{% url 'Stocked:update' 'Units' object.pk %}">update</a>
                <a class="btn btn-sm btn-outline-danger" href="{% url 'Stocked:delete' 'Units' object.pk %}">delete</a>
              </div>
            </td>
          </tr>
        {%  endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No {{template}}!!!</p>
    {% endif %}
  </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>